name: Auto Sync Develop and Master

on:
  workflow_dispatch: # Manually trigger if needed

jobs:
  sync-to-master:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history for merging

      - name: Create and Merge PR from Develop to Master
        env:
          GITHUB_TOKEN: ${{ secrets.DEV_TO_MASTER_SYNC }}
        run: |
          gh pr create --base master --head develop --title "Auto Merge Develop -> Master" --body "Automated merge after production deployment."
          gh pr merge --auto --squash $(gh pr list --base master --head develop --json number --jq '.[0].number')

  sync-back-to-develop:
    needs: sync-to-master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge Master Back into Develop
        env:
          GITHUB_TOKEN: ${{ secrets.DEV_TO_MASTER_SYNC }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout develop
          git merge --no-ff origin/master -m "Sync master -> develop"
          git push origin develop
